name: "docker"
on:
  push:
    branches:
      - master
  pull_request: 
    types: [opened, synchronize, reopened]
  release:
    types:
      - created
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code at current commit"
        uses: actions/checkout@v2
      - name: Prepare
        if: github.event.pull_request.head.repo.full_name == github.repository
        id: Prep
        run: |
          TAGS=sha-${GITHUB_SHA:0:7}
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.pull_request }}-merge
          fi
          if [[ -n $VERSION ]]; then
            TAGS="$TAGS,${{ github.repository }}:${VERSION}"
          fi
          if [[ $VERSION =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="$TAGS,${{ github.repository }}:latest"
          fi
          echo ::set-output name=tags::${TAGS}
      - name: Login to DockerHub
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: "Build and push docker image to DockerHub"
        uses: docker/build-push-action@v2
        with:
          repository: ${{ github.repository }}
          registry: registry-1.docker.io
          push: github.event.pull_request.head.repo.full_name == github.repository
          tags: ${{ steps.prep.outputs.tags }}
